---
- name: "setup.yml"
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: "/usr/libexec/platform-python"

  tasks:
    - name: Update CA bundle
      get_url:
        url: https://curl.haxx.se/ca/cacert.pem
        dest: /etc/pki/tls/certs/ca-bundle.crt
        force: true

    - name: Install epel repo
      dnf:
        name: "epel-release"
        state: latest

    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Install packages
      dnf:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - bash-completion
        - wget
        - nano
        - htop
        - cockpit

    - name: Change Cockpit listen port to 9090
      blockinfile:
        dest: "/etc/systemd/system/cockpit.socket.d/listen.conf"
        create: true
        backup: true
        owner: root
        group: root
        mode: 0755
        state: present
        block: |
          [Socket]
          ListenStream=
          ListenStream=9090

    - name: Add Cockpit port 9090 to Firewalld
      firewalld:
        port: "9090/tcp"
        permanent: true
        immediate: true
        state: enabled

    - name: enable cockpit.socket
      systemd:
        name: cockpit.socket
        enabled: true

    - name: start cockpit
      systemd:
        name: cockpit
        state: started

    - name: Enable ssh password authentication in cloud.cfg
      lineinfile:
        dest: /etc/cloud/cloud.cfg
        regexp: '^ssh_pwauth:'
        line: "ssh_pwauth: 1"
        state: present

    - name: Disable Root ssh login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: false
      become: true
